# Generated by Django 4.0.5 on 2022-06-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newperson',
            old_name='experience',
            new_name='work_experience',
        ),
    ]
